update experiment code and README to work with current psiturk/docker versions

diff --git a/docker/Dockerfile-experiment b/docker/Dockerfile-experiment
--- a/docker/Dockerfile-experiment
+++ b/docker/Dockerfile-experiment
@@ -1,65 +1,41 @@
-# TODO: clean me up
-# Dockerfile for psiturk container
-FROM debian:stretch
-MAINTAINER Paxton Fitzpatrick <paxton.c.fitzpatrick.19@dartmouth.edu>
+# builds an image for running the memory-dynamics experiment
+# Use Dockerfile-analyses to build an environment for reproducing the analyses.
+#
+# Note: the latest release of psiTurk (v3.3.1, October 2022) requires Python
+# 3.9, which is EOL and no longer officially supported.
+# experiment-requirements.txt pins all of psiTurk's dependencies to compatible
+# versions to ensure the experiment still runs.
+FROM python:3.9-slim-bookworm
 
-# install debian-related stuff
-RUN apt-get update
-RUN apt-get install -y eatmydata
-RUN eatmydata apt-get install -y \
-    python-dev \
-    default-libmysqlclient-dev \
-    python-pip \
-    procps \
-    git \
-    yasm
-RUN rm -rf /var/lib/apt/lists/*
+LABEL maintainer="Paxton Fitzpatrick <Paxton.C.Fitzpatrick.GR@Dartmouth.edu>"
 
-# install python packages
-RUN pip install --upgrade pip
-RUN pip install --upgrade \
-setuptools \
-requests \
-mysql-python \
-psiturk==2.2.3 \
-pydub \
-matplotlib \
-pandas \
-numpy \
-quail \
-seaborn \
-hypertools \
-joblib \
-sqlalchemy \
-scipy \
-deepdish
+ARG DEBIAN_FRONTEND=noninteractive \
+    server_port=22363
 
+ENV LANG="C.UTF-8" \
+    LC_ALL="C.UTF-8" \
+    PIP_DISABLE_PIP_VERSION_CHECK=1 \
+    PIP_ROOT_USER_ACTION=ignore \
+    PYTHONDONTWRITEBYTECODE=1 \
+    PSITURK_GLOBAL_CONFIG_LOCATION="/mnt/exp"
 
-# install ffmpeg
-RUN git clone https://github.com/FFmpeg/FFmpeg
-RUN cd FFmpeg && ./configure --enable-gpl && \
-make && make install && ldconfig
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-RUN pip install \
-git+https://github.com/ContextLab/psiTurk.git@expose-gunicorn-timeout-parameter
+RUN --mount=type=bind,source=docker/experiment-requirements.txt,target=/tmp/requirements.txt \
+    sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
+    apt-get update && \
+    apt-get install -y --no-install-recommends \
+        # toolchain for building the handful of psiTurk dependencies with no
+        # prebuilt wheels for Python 3.9 (psutil, setproctitle, etc.)
+        gcc \
+        libc6-dev && \
+    pip install --no-cache-dir -r /tmp/requirements.txt && \
+    # cleanup to reduce image size
+    apt-get purge -y --auto-remove gcc libc6-dev && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/* && \
+    rm -rf "$HOME/.cache/pip"
 
-# install vim
-RUN apt-get update
-RUN apt-get install -y vim
+WORKDIR "/mnt/exp"
 
-# add experiment and data folders
-COPY memory-dynamics/exp /exp
-COPY memory-dynamics/data /data
-COPY memory-dynamics/code /code
-
-# add stimuli folder
-# COPY video-stims /exp/video-stims
-
-# setup working directory
-WORKDIR /exp
-
-# set up psiturk to use the .psiturkconfig in /
-ENV PSITURK_GLOBAL_CONFIG_LOCATION=/
-
-# expose port to access psiturk from outside
-EXPOSE 22363
+CMD ["/bin/bash"]
